import Navbar from "@/components/Navbar";
import "../globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "eCommerce",
  description: "Generated by Next + Sanity + Vercel",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <header>
        <Navbar />
      </header>
      <body>{children}</body>
      <Footer />
    </html>
  );
}
